version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - 178inaba
  - package-ecosystem: docker
    directories:
      - /firestore
      - /pubsub
    schedule:
      interval: daily
    assignees:
      - 178inaba
